# Generated by Django 4.0.6 on 2022-08-20 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoriesImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='Clothing', verbose_name='Image')),
            ],
        ),
        migrations.RenameModel(
            old_name='Hair',
            new_name='Cosmetics',
        ),
        migrations.RenameModel(
            old_name='HairImages',
            new_name='CosmeticsImages',
        ),
        migrations.RenameModel(
            old_name='Perfumes',
            new_name='Gadgets',
        ),
        migrations.RenameModel(
            old_name='PerfumesImages',
            new_name='GadgetsImages',
        ),
        migrations.AlterField(
            model_name='clothingimages',
            name='entry',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='footwearphoto', to='homeapp.clothing'),
        ),
        migrations.AlterField(
            model_name='clothingimages',
            name='images',
            field=models.ImageField(upload_to='Footwear', verbose_name='Image'),
        ),
        migrations.RenameModel(
            old_name='Footwear',
            new_name='Accessories',
        ),
        migrations.DeleteModel(
            name='FootwearImages',
        ),
        migrations.AddField(
            model_name='accessoriesimages',
            name='entry',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='clothingphoto', to='homeapp.accessories'),
        ),
    ]
