# Generated by Django 4.0.6 on 2023-05-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_accessoriesimages_rename_hair_cosmetics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseAcc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenseitem', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeAcc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incomeitem', models.CharField(max_length=10)),
            ],
        ),
    ]
