# Generated by Django 4.0.6 on 2023-05-20 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_expenseacc_incomeacc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incomeentries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('incomename', models.CharField(max_length=10)),
                ('incomeorigin', models.CharField(max_length=10)),
                ('incometype', models.CharField(max_length=10)),
                ('incomeamount', models.FloatField(blank=True, null=True)),
                ('entry', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='incomeentred', to='homeapp.incomeacc')),
            ],
        ),
        migrations.CreateModel(
            name='Expenseentries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('expenseplace', models.CharField(max_length=10)),
                ('expensetype', models.CharField(max_length=10)),
                ('expenseamount', models.FloatField(blank=True, null=True)),
                ('expensename', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='expenseentred', to='homeapp.expenseacc')),
            ],
        ),
    ]
